name: tlc_nyc
description: "A new Flutter project."
publish_to: 'none'  
version: 1.0.0+1

environment:
  sdk: ^3.7.2 
dependencies:
  flutter:
    sdk: flutter 
  cupertino_icons: ^1.0.8
  get: 
  flutter_screenutil:
  flutter_secure_storage: ^9.2.4 
  pinput: ^5.0.1
  flutter_svg: ^2.2.0
  dio:
  firebase_core: ^4.2.1
  image_picker: ^1.2.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter 
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/tlc_nyc.png"
  min_sdk_android: 21  
  web:
    generate: true
    image_path: "assets/images/tlc_nyc.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/images/tlc_nyc.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/images/tlc_nyc.png"
 
flutter:
 
  uses-material-design: true
 
  assets:
    - assets/images/
    - assets/svg/
    - assets/question.json 
